# Generated by Django 5.0.6 on 2024-06-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('major', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('classification', models.CharField(max_length=20)),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
                ('professor', models.CharField(max_length=50)),
                ('timetable_period', models.CharField(max_length=100)),
                ('timetable_time', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('class_type', models.CharField(max_length=20)),
            ],
        ),
    ]
